# Generated by Django 3.2.2 on 2021-05-12 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='advisors',
            name='image_file',
            field=models.ImageField(blank=True, upload_to='images'),
        ),
    ]
